name: Continuous Deployment Production Or Live Branch

on:
  push:
    branches:
      - "main"

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v2

      - run: chmod +x ./gradlew

      - name: decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: build release apk
        run: ./gradlew assembleProductionRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}

      # google drive app distribution
      - name: upload to google drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: "app/build/outputs/apk/production/release/app-production-release.apk"
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          parent_folder_id: ${{ secrets.GDRIVE_FOLDER_ID }}

      # firebase app distribution
#      - name: upload to firebase app distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{ secrets.FIREBASE_APP_ID }}
#          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
#          file: app/build/outputs/apk/production/release/app-production-release.apk
#          groups: production