name: Continuous Integration Pull Request

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"
      - "chore/**"
  pull_request:
    branches:
      - "develop"
      - "staging"
      - "main"
    # only run if relevant files change
    paths:
      - '**.kt'
      - '**.xml'
      - '**.gradle*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v2

      - run: chmod +x ./gradlew

      - name: Verify Compilation (All Flavors)
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          # Using 'assemble' with no flavor suffix can be slow.
        # It's better to pick one main flavor for CI check:
        run: ./gradlew :app:assembleDevDebug --dry-run

      - name: run unit tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: ./gradlew test